/**
 * DSH Projects Phase 3 — Coordinator session driver (spec §5.3).
 *
 * `CoordinatorDriver` is the narrow seam the `CoordinatorService` talks to: one
 * Lead session, one prompt, one structured submission callback. The default
 * `HarnessCoordinatorDriver` mirrors the `HarnessAgentRunner` mechanics —
 * `ctx.agents.create` + `setup` tool registration (`defineTool`), one user
 * message, `whenIdle`, `flush`, turn-end reason, `dispose`.
 */

import type { Context } from '@deepseek-ai/cordis'
import { installModelSelection, type AgentHandle, type ModelSelectionRef } from '@deepseek-ai/dsh-agent'
import type {} from '@deepseek-ai/dsh-agent-default-model'
import type {} from '@deepseek-ai/dsh-agent-presets'
import { createUserMessage } from '@deepseek-ai/dsh-llm'
import { SessionId, type SessionEvent } from '@deepseek-ai/dsh-session'
import type {} from '@deepseek-ai/dsh-permission-presets'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type {} from '@deepseek-ai/dsh-tools'
import { RUN_PLAN_PATTERNS } from '../plans/spec.ts'
import type { PlanId, RunPlanPattern, RunPlanStatus } from '../plans/types.ts'

/** One structured plan submission from the Lead session (spec §5.3). */
export interface CoordinatorPlanSubmission {
  readonly pattern: RunPlanPattern
  readonly rationale: string
  readonly assumptions?: readonly string[]
  readonly successCriteria?: readonly string[]
  readonly tasks?: readonly {
    readonly title: string
    readonly description: string
    readonly dependencies?: readonly string[]
    readonly acceptanceCriteria?: readonly string[]
  }[]
  /** Required when a prior plan version already exists for the run. */
  readonly replanReason?: string
  /** Concise human-facing planning summary; persisted, not part of the plan. */
  readonly summary: string
}

/** Reference of the plan created by a successful submission. */
export interface CoordinatorPlanSubmitted {
  readonly planId: PlanId
  readonly version: number
  readonly pattern: RunPlanPattern
  readonly status: RunPlanStatus
}

/** One driver invocation: one Lead session, one prompt. */
export interface CoordinatorDriverInput {
  /** Prefixed session id (`dsh-coordinator-<uuid>`), generated by the service. */
  readonly sessionId: string
  readonly cwd: string
  readonly permissionPreset: string
  readonly agentPreset?: string
  readonly prompt: string
  readonly signal: AbortSignal
  readonly onPlanSubmit: (input: CoordinatorPlanSubmission) => Promise<CoordinatorPlanSubmitted>
}

export interface CoordinatorDriverResult {
  readonly kind: 'completed' | 'failed' | 'blocked'
  readonly error?: string
}

/** The seam the CoordinatorService depends on (tests inject a fake). */
export interface CoordinatorDriver {
  start(input: CoordinatorDriverInput): Promise<CoordinatorDriverResult>
}

/** Native Harness implementation of the coordinator session driver. */
export class HarnessCoordinatorDriver {
  constructor(private readonly ctx: Context) {}

  async start(input: CoordinatorDriverInput): Promise<CoordinatorDriverResult> {
    if (input.signal.aborted) return { kind: 'failed', error: 'coordinator session aborted' }
    const sessionId = SessionId(input.sessionId)
    const selection = this.ctx.agentDefaultModel.currentSelection()
    const selected: ModelSelectionRef = { current: selection, assembled: undefined }
    const presets = this.ctx.get('agentPresets')
    if (input.agentPreset !== undefined && presets === undefined) {
      return { kind: 'failed', error: `agentPreset ${JSON.stringify(input.agentPreset)} is configured but ctx.agentPresets is unavailable` }
    }
    const resolvedPreset = presets === undefined ? undefined : await presets.resolve(input.agentPreset)

    let handle: AgentHandle | undefined
    const onAbort = (): void => {
      handle?.agent.cancel({ kind: 'hook', reason: 'dsh-projects coordination cancelled' })
    }
    input.signal.addEventListener('abort', onAbort, { once: true })
    try {
      handle = await this.ctx.agents.create({
        sessionId,
        meta: {
          cwd: input.cwd,
          ...(resolvedPreset === undefined ? {} : { agentPreset: resolvedPreset.id }),
        },
        agentOptions: { provider: selection.provider, model: selection.model },
        signal: input.signal,
        setup: async (agentCtx) => {
          if (presets !== undefined) await presets.mount(agentCtx, resolvedPreset?.id)
          installModelSelection(agentCtx, selected)
          this.installSubmitPlanTool(agentCtx, input.onPlanSubmit)
        },
      })
      this.ctx.permissionPresets.set(handle.agent.session, input.permissionPreset)
      const firstSeq = handle.agent.session.seq
      handle.agent.followup(createUserMessage({
        content: [{ type: 'text', text: input.prompt }],
        source: { kind: 'user' },
      }))
      await handle.agent.whenIdle()
      await this.ctx.sessions.flush(handle.agent.session)
      const end = lastTurnEnd(handle.agent.session.events, firstSeq)
      if (end?.data.reason.kind === 'error') {
        return { kind: 'failed', error: `${end.data.reason.error.code}: ${end.data.reason.error.message}` }
      }
      if (end?.data.reason.kind === 'blocked') {
        return { kind: 'blocked', error: 'the coordinator session ended blocked' }
      }
      if (end?.data.reason.kind !== 'completed') {
        return { kind: 'failed', error: `the coordinator session ended as ${end?.data.reason.kind ?? 'unknown'}` }
      }
      return { kind: 'completed' }
    } catch (error) {
      return { kind: 'failed', error: error instanceof Error ? error.message : String(error) }
    } finally {
      input.signal.removeEventListener('abort', onAbort)
      if (handle !== undefined) {
        try {
          await this.ctx.sessions.flush(handle.agent.session)
        } finally {
          await handle.dispose()
        }
      }
    }
  }

  /** Register `dsh_projects_submit_plan` in the session scope (spec §5.4). */
  private installSubmitPlanTool(agentCtx: Context, onPlanSubmit: CoordinatorDriverInput['onPlanSubmit']): void {
    const tools = agentCtx.get('tools')
    if (tools === undefined) throw new Error('dsh-projects: ctx.tools is unavailable in the Agent scope')
    tools.register(defineTool({
      name: 'dsh_projects_submit_plan',
      description: 'Submit the versioned Run Plan for this coordination. Call exactly once with the complete plan.',
      parameters: {
        pattern: {
          type: 'string',
          enum: [...RUN_PLAN_PATTERNS],
          required: true,
          description: 'The coordination pattern chosen for this plan.',
        },
        rationale: { type: 'string', required: true, description: 'Why this plan serves the run goal.' },
        assumptions: { type: 'array', items: { type: 'string' }, description: 'Stated assumptions.' },
        successCriteria: { type: 'array', items: { type: 'string' }, description: 'Plain success criteria.' },
        tasks: {
          type: 'array',
          description: 'Planned tasks; ids t1..tN are assigned by the service in list order.',
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              title: { type: 'string', required: true },
              description: { type: 'string', required: true },
              dependencies: { type: 'array', items: { type: 'string' }, description: 'Ids of EARLIER tasks only.' },
              acceptanceCriteria: { type: 'array', items: { type: 'string' } },
            },
          },
        },
        replanReason: { type: 'string', description: 'REQUIRED when a prior plan version exists for this run.' },
        summary: { type: 'string', required: true, description: 'Concise human-facing planning summary.' },
      },
      output: {
        schema: { type: 'json' },
        render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }],
      },
      async execute(args) {
        if (!RUN_PLAN_PATTERNS.includes(args.pattern)) {
          throw new Error(`unknown plan pattern ${String(args.pattern)}`)
        }
        const submission: CoordinatorPlanSubmission = {
          pattern: args.pattern,
          rationale: args.rationale,
          ...(args.assumptions === undefined ? {} : { assumptions: args.assumptions }),
          ...(args.successCriteria === undefined ? {} : { successCriteria: args.successCriteria }),
          ...(args.tasks === undefined ? {} : {
            tasks: args.tasks.map(task => ({
              title: task.title,
              description: task.description,
              ...(task.dependencies === undefined ? {} : { dependencies: task.dependencies }),
              ...(task.acceptanceCriteria === undefined ? {} : { acceptanceCriteria: task.acceptanceCriteria }),
            })),
          }),
          ...(args.replanReason === undefined ? {} : { replanReason: args.replanReason }),
          summary: args.summary,
        }
        const submitted = await onPlanSubmit(submission)
        return submitted as never
      },
    }))
  }
}

function lastTurnEnd(events: readonly SessionEvent[], firstSeq: number): SessionEvent<'turn/end'> | undefined {
  return events.filter((event): event is SessionEvent<'turn/end'> => event.seq >= firstSeq && event.type === 'turn/end').at(-1)
}
