/**
 * DSH Projects Phase 6 — Run memory distillation (spec §6).
 *
 * `MemoryDistillationDriver` is the narrow seam the `ProjectMemoryService`
 * talks to: one distiller session, one prompt, one structured submission
 * callback. The default `HarnessMemoryDistillationDriver` mirrors
 * `HarnessCoordinatorDriver` line-for-line in mechanics — `ctx.agents.create`
 * + `setup` tool registration (`defineTool`), one user message, `whenIdle`,
 * `flush`, turn-end reason, `dispose`. No new Harness API is touched.
 */

import type { Context } from '@deepseek-ai/cordis'
import { installModelSelection, type AgentHandle, type ModelSelectionRef } from '@deepseek-ai/dsh-agent'
import type {} from '@deepseek-ai/dsh-agent-default-model'
import type {} from '@deepseek-ai/dsh-agent-presets'
import { createUserMessage } from '@deepseek-ai/dsh-llm'
import { SessionId, type SessionEvent } from '@deepseek-ai/dsh-session'
import type {} from '@deepseek-ai/dsh-permission-presets'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type {} from '@deepseek-ai/dsh-tools'
import { MEMORY_KINDS } from './types.ts'

/** One structured memory submission from the distiller session (spec §6.1). */
export interface MemoryDistillationSubmission {
  readonly entries: readonly {
    readonly kind: string
    readonly title: string
    readonly body: string
    readonly tags?: readonly string[]
    readonly confidence?: number
    readonly sourceTaskId?: string
  }[]
}

/** One driver invocation: one distiller session, one prompt (spec §6.1). */
export interface MemoryDistillationDriverInput {
  /** Prefixed session id (`dsh-memory-<uuid>`), generated by the service. */
  readonly sessionId: string
  readonly cwd: string
  readonly permissionPreset: string
  readonly agentPreset?: string
  readonly prompt: string
  readonly signal: AbortSignal
  readonly onMemorySubmit: (input: MemoryDistillationSubmission) =>
    Promise<{ readonly persisted: number; readonly superseded: number }>
}

export interface MemoryDistillationDriverResult {
  readonly kind: 'completed' | 'failed' | 'blocked'
  readonly error?: string
}

/** The seam the ProjectMemoryService depends on (tests inject a fake). */
export interface MemoryDistillationDriver {
  start(input: MemoryDistillationDriverInput): Promise<MemoryDistillationDriverResult>
}

/** The distillation session must not modify the project repository. */
export const MEMORY_DISTILLATION_PERMISSION_PRESET = 'workspace-write'

/** Raw shape of the `dsh_projects_submit_memory` tool arguments. */
interface SubmitMemoryArgs {
  readonly entries?: readonly {
    readonly kind: string
    readonly title: string
    readonly body: string
    readonly tags?: readonly string[]
    readonly confidence?: number
    readonly sourceTaskId?: string
    readonly note?: string
  }[]
}

/** Native Harness implementation of the memory distillation driver. */
export class HarnessMemoryDistillationDriver {
  constructor(private readonly ctx: Context) {}

  async start(input: MemoryDistillationDriverInput): Promise<MemoryDistillationDriverResult> {
    if (input.signal.aborted) return { kind: 'failed', error: 'memory distillation session aborted' }
    const sessionId = SessionId(input.sessionId)
    const selection = this.ctx.agentDefaultModel.currentSelection()
    const selected: ModelSelectionRef = { current: selection, assembled: undefined }
    const presets = this.ctx.get('agentPresets')
    if (input.agentPreset !== undefined && presets === undefined) {
      return { kind: 'failed', error: `agentPreset ${JSON.stringify(input.agentPreset)} is configured but ctx.agentPresets is unavailable` }
    }
    const resolvedPreset = presets === undefined ? undefined : await presets.resolve(input.agentPreset)

    let handle: AgentHandle | undefined
    const onAbort = (): void => {
      handle?.agent.cancel({ kind: 'hook', reason: 'dsh-projects memory distillation cancelled' })
    }
    input.signal.addEventListener('abort', onAbort, { once: true })
    try {
      handle = await this.ctx.agents.create({
        sessionId,
        meta: {
          cwd: input.cwd,
          ...(resolvedPreset === undefined ? {} : { agentPreset: resolvedPreset.id }),
        },
        agentOptions: { provider: selection.provider, model: selection.model },
        signal: input.signal,
        setup: async (agentCtx) => {
          if (presets !== undefined) await presets.mount(agentCtx, resolvedPreset?.id)
          installModelSelection(agentCtx, selected)
          this.installSubmitMemoryTool(agentCtx, input.onMemorySubmit)
        },
      })
      this.ctx.permissionPresets.set(handle.agent.session, input.permissionPreset)
      const firstSeq = handle.agent.session.seq
      handle.agent.followup(createUserMessage({
        content: [{ type: 'text', text: input.prompt }],
        source: { kind: 'user' },
      }))
      await handle.agent.whenIdle()
      await this.ctx.sessions.flush(handle.agent.session)
      const end = lastTurnEnd(handle.agent.session.events, firstSeq)
      if (end?.data.reason.kind === 'error') {
        return { kind: 'failed', error: `${end.data.reason.error.code}: ${end.data.reason.error.message}` }
      }
      if (end?.data.reason.kind === 'blocked') {
        return { kind: 'blocked', error: 'the memory distillation session ended blocked' }
      }
      if (end?.data.reason.kind !== 'completed') {
        return { kind: 'failed', error: `the memory distillation session ended as ${end?.data.reason.kind ?? 'unknown'}` }
      }
      return { kind: 'completed' }
    } catch (error) {
      return { kind: 'failed', error: error instanceof Error ? error.message : String(error) }
    } finally {
      input.signal.removeEventListener('abort', onAbort)
      if (handle !== undefined) {
        try {
          await this.ctx.sessions.flush(handle.agent.session)
        } finally {
          await handle.dispose()
        }
      }
    }
  }

  /** Register `dsh_projects_submit_memory` in the session scope (spec §6.1). */
  private installSubmitMemoryTool(agentCtx: Context, onMemorySubmit: MemoryDistillationDriverInput['onMemorySubmit']): void {
    const tools = agentCtx.get('tools')
    if (tools === undefined) throw new Error('dsh-projects: ctx.tools is unavailable in the Agent scope')
    tools.register(defineTool({
      name: 'dsh_projects_submit_memory',
      description: 'Submit the durable memory entries distilled from this run. Call exactly once with all entries — an empty array is a valid answer when nothing is reusable.',
      parameters: {
        entries: {
          type: 'array',
          description: 'Memory entries distilled from the run; an empty array means nothing is reusable.',
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              kind: { type: 'string', enum: [...MEMORY_KINDS], required: true, description: 'The memory kind.' },
              title: { type: 'string', required: true, description: 'Short factual title (max 200 chars).' },
              body: { type: 'string', required: true, description: 'The durable fact or procedure (max 12000 chars).' },
              tags: { type: 'array', items: { type: 'string' }, description: 'Optional tags (max 20 tags, 40 chars each).' },
              confidence: { type: 'number', description: 'Optional confidence in [0, 1].' },
              sourceTaskId: { type: 'string', description: 'Optional id of the task this entry came from.' },
              note: { type: 'string', description: 'Optional free-form note about the submission.' },
            },
          },
        },
      },
      output: {
        schema: { type: 'json' },
        render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }],
      },
      async execute(args: SubmitMemoryArgs) {
        const entries = (args.entries ?? []).map(entry => ({
          kind: entry.kind,
          title: entry.title,
          body: entry.body,
          ...(entry.tags === undefined ? {} : { tags: entry.tags }),
          ...(entry.confidence === undefined ? {} : { confidence: entry.confidence }),
          ...(entry.sourceTaskId === undefined || entry.sourceTaskId === '' ? {} : { sourceTaskId: entry.sourceTaskId }),
        }))
        const counts = await onMemorySubmit({ entries })
        return counts as never
      },
    }))
  }
}

/**
 * Build the distillation prompt (spec §6.2) from persisted data only:
 * identity, the run goal, per-task outcome lines, already-stored titles,
 * and the master-spec §21 write policy. Pure and deterministic.
 */
export interface DistillationPromptInput {
  readonly goal: string
  readonly tasks: readonly {
    readonly planTaskId: string
    readonly title: string
    readonly status: string
    readonly outputSummary?: string
  }[]
  /** Titles of the project's active entries (already fetched by the service). */
  readonly existingTitles: readonly string[]
}

const MAX_TASK_SUMMARY_LENGTH = 400
const MAX_EXISTING_TITLE_LENGTH = 120
const MAX_EXISTING_TITLES = 25

function truncate(value: string, max: number): string {
  return value.length <= max ? value : `${value.slice(0, max - 1)}…`
}

const WRITE_POLICY = [
  'WRITE POLICY (persist only reusable project knowledge):',
  'Good memory examples:',
  '- Integration tests require PostgreSQL and Redis.',
  '- The auth service uses Azure OBO token exchange.',
  "- The repository's generated API client must be regenerated using pnpm generate:api after schema changes.",
  '- Do not modify src/generated manually.',
  '- CI fails if migrations are not formatted with dbmate fmt.',
  'Bad memory examples (do NOT persist):',
  '- Agent spent 11 minutes reading files.',
  '- The user said "thanks".',
  '- npm install was slow once.',
  '- Agent attempted command X and then changed its mind.',
  'Before persisting, consider:',
  '- Is this likely useful in another run?',
  '- Is it project-specific?',
  '- Is it still true?',
  '- Is it already stored? (see the already-stored list; do not resubmit duplicates)',
  '- Does it contain secrets? (never submit secrets, credentials, or transcript dumps)',
  'Submit zero entries if nothing is reusable.',
].join('\n')

export function buildDistillationPrompt(input: DistillationPromptInput): string {
  const taskLines = input.tasks
    .filter(task => task.status === 'succeeded' || task.status === 'failed')
    .map(task => {
      const line = `${task.planTaskId} [${task.status}] ${task.title}`
      return task.outputSummary === undefined || task.outputSummary === ''
        ? line
        : `${line} — ${truncate(task.outputSummary, MAX_TASK_SUMMARY_LENGTH)}`
    })
  const sections: string[] = []
  sections.push('You are distilling durable project memory from a completed run.')
  sections.push(`Run goal: ${input.goal}`)
  sections.push(taskLines.length === 0
    ? 'Tasks: none with a terminal outcome.'
    : `Tasks (real persisted results only):\n${taskLines.join('\n')}`)
  const stored = input.existingTitles.slice(0, MAX_EXISTING_TITLES).map(title => truncate(title, MAX_EXISTING_TITLE_LENGTH))
  sections.push(stored.length === 0
    ? 'Already stored (do not resubmit duplicates): none'
    : `Already stored (do not resubmit duplicates):\n${stored.map(title => `- ${title}`).join('\n')}`)
  sections.push(WRITE_POLICY)
  return sections.join('\n\n')
}

function lastTurnEnd(events: readonly SessionEvent[], firstSeq: number): SessionEvent<'turn/end'> | undefined {
  return events.filter((event): event is SessionEvent<'turn/end'> => event.seq >= firstSeq && event.type === 'turn/end').at(-1)
}
